title: Tips for Career Transitioners wanting to get into Information Security
author: Hil (robot_wombat)
email: your-email@domain.com
description: Blog about how one person got into the information security field with no prior IT experience.
twitter_username: robot_wombat
github_username:  friendlyrobotwombat

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
